notification-messages:
  types:
    LIKED_ON_COLLECTION:
      push-title: "{actorName}"
      push-body: "나의 새록을 좋아해요."
    COMMENTED_ON_COLLECTION:
      push-title: "{actorName}"
      push-body: "나의 새록에 댓글을 남겼어요. \"{comment}\""
    SUGGESTED_BIRD_ID_ON_COLLECTION:
      push-title: "동정 의견 공유"
      push-body: "두근두근! 새로운 의견이 공유되었어요. 확인해볼까요?"
    SYSTEM_PUBLISHED_ANNOUNCEMENT:
      push-title: "{title}"
      push-body: "{body}"